name: Update PocketBase Version

on:
  schedule:
    - cron: '0 0 * * *' # Ejecutar diariamente
  workflow_dispatch: # Permite ejecución manual

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest PocketBase Version
        id: get_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/pocketbase/pocketbase/releases/latest | jq -r '.tag_name')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/PB_VERSION=[0-9.]\+/PB_VERSION=${{ env.LATEST_VERSION }}/g" README.md

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update PocketBase version to ${{ env.LATEST_VERSION }}"
          branch: main
